language: python
python:
  - '3.6'
  - '2.7'

install: skip
script:
  # prepare python modules
  - pip install -r requirements.txt
  - pip install coverage
  # python tests
  - >
    cd tests && 
    PYTHONPATH=../src python -m coverage run --branch --source=../src -m unittest discover -v
  # coverage reports
  - python -m coverage report -m

jobs:
  include:
    - &deploy-stage
      stage: deploy
      if: branch = master
      sudo: true
      script:
        - docker run --rm --privileged multiarch/qemu-user-static:register --reset
        - |
          docker build -t redirect-server:$DOCKER_TAG    \
            --build-arg GIT_COMMIT=$TRAVIS_COMMIT        \
            --build-arg BUILD_TIMESTAMP=$(date +%s)      \
            -f $DOCKERFILE .
        - docker tag redirect-server:$DOCKER_TAG rycus86/redirect-server:$DOCKER_TAG
        # smoke tests
        - mkdir smoke
        - |
          cat << EOF > smoke/rules.yml
          rules:
            - source: /simple
              target: http://test.sample/check-simple
            - source: /regex/(.+)
              target: http://test.regex/\1
              regex:  true

          admin:
            path: /admin
            username: smoke
            password: testing
          EOF
        - |
          docker run -d -p 5000:5000 -e HTTP_HOST=0.0.0.0  \
              -e RULES_DIR=/smoke -v $PWD/smoke:/smoke:ro  \
              redirect-server:$DOCKER_TAG
        - curl -fsv http://localhost:5000/simple 2>&1 | grep '< Location: http://test.sample/check-simple'
        - curl -fsv http://localhost:5000/regex/first 2>&1 | grep '< Location: http://test.regex/first'
        - curl -fsv http://localhost:5000/regex/second 2>&1 | grep '< Location: http://test.regex/second'
        - curl -fsv -u 'smoke:testing' http://localhost:5000/admin | grep '< HTTP/1.0 200 OK'
      after_success:
        - docker login -u="rycus86" -p="$DOCKER_PASSWORD"
        - docker push rycus86/redirect-server:$DOCKER_TAG
      env:
        - DOCKER_TAG=amd64
        - DOCKERFILE=Dockerfile

    - <<: *deploy-stage
      env:
        - DOCKER_TAG=armhf
        - DOCKERFILE=Dockerfile.armhf

    - <<: *deploy-stage
      env:
        - DOCKER_TAG=aarch64
        - DOCKERFILE=Dockerfile.aarch64

    - stage: manifest
      if: branch = master
      sudo: true
      script:
        - docker login -u="rycus86" -p="${DOCKER_PASSWORD}"
        - curl -fsSL https://github.com/estesp/manifest-tool/releases/download/v0.7.0/manifest-tool-linux-amd64 > ./manifest-tool
        - chmod +x ./manifest-tool
        - ./manifest-tool push from-spec manifest.yml
